version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: db_admin_pass
      MYSQL_DATABASE: HomeDashboardDB
      MYSQL_USER: sql
      MYSQL_PASSWORD: your_password
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadminHomeDashboard:
    image: phpmyadmin:latest
    container_name: phpmyadminHomeDashboard
    depends_on:
      - db
    restart: on-failure
    environment:
      PMA_HOST: mariadbHomeDashboard
      PMA_ARBITRARY: 1
    ports:
      - "85:80"

  webserver-home-dashboard:
    container_name: webserver-home-dashboard
    build:
      context: ./dockerFiles
      dockerfile: webserver.Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    depends_on:
        - db
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/HomeDashboard

volumes:
  mysql: {}